---
- include_vars: twitter_api_keys.yml

- name: Creates Twitalyzr directory
  file:
    path: "{{twitalyzr_dir}}"
    state: directory
    mode: u+rwx

- name: Copy Twitalyzr JAR
  copy:
      src: "{{twitalyzr_src_jar}}"
      dest: "{{twitalyzr_dir}}/{{twitalyzr_jar_name}}"

- name: Copy Twitalyzr Model
  unarchive:
      copy: yes
      src: "{{twitalyzr_src_model}}"
      dest: "{{twitalyzr_dir}}"
      mode: u+rwx

- name: Copy Twitalyzr Configuration
  template:
      src: "application.conf.j2"
      dest: "{{twitalyzr_dir}}/{{twitalyzr_conf_name}}"