---
java_version: java8jre

spark_conf_vars:
  spark_master_ip: '0.0.0.0:7077'

twitalyzr_dir: "/home/ubuntu/twitalyzr"
twitalyzr_jar_name: "twitalyzr-assembly-0.1-SNAPSHOT.jar"
twitalyzr_jar: "{{twitalyzr_dir}}/{{twitalyzr_jar_name}}"
twitalyzr_model_name: "model.dat"
twitalyzr_model_dir: "{{twitalyzr_dir}}/{{twitalyzr_model_name}}"
