---
java_version: java8jre

spark_conf_vars:
  spark_master_ip: '0.0.0.0:7077'

twicas_dir: "/home/ubuntu/twicas"
twicas_jar_name: "twicas-assembly-0.1-SNAPSHOT.jar"
twicas_jar: "{{twicas_dir}}/{{twicas_jar_name}}"
twicas_model_name: "model.dat"
twicas_model_dir: "{{twicas_dir}}/{{twicas_model_name}}"
